#!/bin/bash

if [ -n $1 ] || [ -n $2 ]
then
    echo "Insufficient parameters! Usage: eval2csv [ LOG DIRECTORY ] [ PATH TO CSV ]"
    exit
fi

logDirectory=$1
csvFile=$2

touch ${csvFile}
for l in ${logDirectory}/*-eval.log
do
    read -r requests minSize maxSize maxSeed pageSize < "${l}"
    i=0
	line=`grep "mara" ${l}`
	echo ${line}
    for number in ${line}
    do
        echo ${number}
        case ${i} in
            1)
            total=${number}
            ;;
            2)
            factor=${number}
            ;;
            *)
            ;;
        esac
        i=$((i+1))
    done
    if [ -n ${requests} ] && [ -n ${minSize} ] && [ -n ${maxSize} ] && [ -n ${maxSeed} ] && [ -n ${pageSize} ]
    then
        requests=${requests#requests=}
        minSize=${minSize#minSize=}
        maxSize=${maxSize#maxSize=}
        pageSize=${pageSize#pageSize=}
        echo "${requests},${minSize},${maxSize},${pageSize},${total},${factor}" >> ${csvFile}
    fi
done