#!/bin/bash

################################################################################
#                                                                              #
#  This script takes a folder with logfiles and compresses the results of      #
#  the testruns into a single csv file (Parameter #2).                         #
#                                                                              #
################################################################################

if [ -z $1 ] || [ -z $2 ]
then
    echo "Insufficient parameters! Usage: eval2csv [ LOG DIRECTORY ] [ PATH TO CSV ]"
    exit
fi

logDirectory=$1
csvFile=$2

touch ${csvFile}
echo requests,minsize,maxsize,pagesize,totaltime,factormalloc >> ${csvFile}

for l in ${logDirectory}/*-eval.log
do
    read -r requests minSize maxSize maxSeed pageSize < "${l}"
    #echo "${requests},${minSize},${maxSize},${pageSize},${total},${factor}"
    i=0
	line=`grep "mara" ${l}`
	#echo ${line}
    for number in ${line}
    do
        #echo ${number}
        case ${i} in
            1)
            total=${number}
            #echo read total: ${number}
            ;;
            3)
            factor=${number}
            #echo read factor: ${number}
            ;;
            *)
            ;;
        esac
        i=$((i+1))
    done
    lastLine=`grep "memory requested" ${l}`
    errors=${lastLine#*blocks: }
    errors=${errors%%, *}
    pageLoad=${lastLine#*page load: }
    pageLoad=${pageLoad%%,*}
    memory=${lastLine#*memory requested: }
    memory=${memory%% *}
    if [ -n ${requests} ] && [ -n ${minSize} ] && [ -n ${maxSize} ] && [ -n ${maxSeed} ] && [ -n ${pageSize} ]
    then
        requests=${requests#requests=}
        minSize=${minSize#minSize=}
        maxSize=${maxSize#maxSize=}
        pageSize=${pageSize#pageSize=}
        echo "${requests},${minSize},${maxSize},${pageSize},${total},${factor},${pageLoad},${memory},${errors}"
        echo "${requests},${minSize},${maxSize},${pageSize},${total},${factor},${pageLoad},${memory},${errors}" >> ${csvFile}
    fi
done
